// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SakhCuba.Models;

namespace SakhCuba.Migrations
{
    [DbContext(typeof(SakhCubaContext))]
    [Migration("20211005063718_IpAndDateAdd")]
    partial class IpAndDateAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SakhCuba.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(10000);

                    b.Property<float>("Age");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("DecisionId");

                    b.Property<string>("DiscordName");

                    b.Property<string>("FavoriteBook")
                        .IsRequired();

                    b.Property<string>("IP");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Nickname")
                        .IsRequired();

                    b.Property<string>("ReasonToPlay")
                        .IsRequired();

                    b.Property<string>("Rules")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("SakhCuba.Models.Decision", b =>
                {
                    b.Property<int>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DecisionName");

                    b.HasKey("DecisionId");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("SakhCuba.Models.Application", b =>
                {
                    b.HasOne("SakhCuba.Models.Decision", "Decision")
                        .WithMany("Applications")
                        .HasForeignKey("DecisionId");
                });
#pragma warning restore 612, 618
        }
    }
}
